INSERT INTO category (code, name) VALUES (1, 'Dogs');
INSERT INTO category (code, name) VALUES (2, 'Cats');
INSERT INTO category (code, name) VALUES (3, 'Fishes');

INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Pretinha', 'Pinscher is a type of dog developed originally as ratters on farms and for fighting or guarding, although today they are most often kept as pets. The breed is powerful and muscular with an elegant appearance. It originated from Germany.', 1, 'AVAILABLE', CURRENT_DATE(),'dog.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Lilinho', 'Pinscher is a type of dog developed originally as ratters on farms and for fighting or guarding, although today they are most often kept as pets. The breed is powerful and muscular with an elegant appearance. It originated from Germany.', 1, 'AVAILABLE', CURRENT_DATE(),'dog1.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Xuxa', 'Generally considered dogkinds finest all-purpose worker, the German Shepherd Dog is a large, agile, muscular dog of noble character and high intelligence. Loyal, confident, courageous, and steady, the German Shepherd is truly a dog lovers delight.', 1, 'ADOPTED', CURRENT_DATE(),'dog1.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Troica', 'Generally considered dogkinds finest all-purpose worker, the German Shepherd Dog is a large, agile, muscular dog of noble character and high intelligence. Loyal, confident, courageous, and steady, the German Shepherd is truly a dog lovers delight.', 1, 'ADOPTED', CURRENT_DATE(),'dog1.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Fani', 'Pinscher is a type of dog developed originally as ratters on farms and for fighting or guarding, although today they are most often kept as pets. The breed is powerful and muscular with an elegant appearance. It originated from Germany.', 1, 'ADOPTED', CURRENT_DATE()+1,'dog1.png', '');

INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Garfield', 'The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth, and retractable claws adapted to killing small prey like mice and rats. Its night vision and sense of smell are well developed.', 2, 'AVAILABLE', CURRENT_DATE(),'cat.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Frodo', 'The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth, and retractable claws adapted to killing small prey like mice and rats. Its night vision and sense of smell are well developed.', 2, 'AVAILABLE', CURRENT_DATE(),'cat.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Xena', 'The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth, and retractable claws adapted to killing small prey like mice and rats. Its night vision and sense of smell are well developed.', 2, 'ADOPTED', CURRENT_DATE(),'cat1.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Eliseu', 'The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth, and retractable claws adapted to killing small prey like mice and rats. Its night vision and sense of smell are well developed.', 2, 'ADOPTED', CURRENT_DATE(),'cat1.png', '');
INSERT INTO animal (id, name, description, category_code, status, created_at, file_name, imageurl) VALUES (random_uuid(), 'Agnes', 'The cat is similar in anatomy to the other felid species: it has a strong flexible body, quick reflexes, sharp teeth, and retractable claws adapted to killing small prey like mice and rats. Its night vision and sense of smell are well developed.', 2, 'AVAILABLE', CURRENT_DATE(),'cat1.png', '');